#!/usr/bin/env bash
# displays Best School 10 times and "Hi" in the 9th time

COUNTER=1
while [ $COUNTER -lt 11 ]
do
	echo "Best School"
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    fi
      
   
    COUNTER=$((COUNTER+1))
done
