#!/usr/bin/env bash
# a bash script that prints 1-20 and bad luck in multiple countries
COUNTER=1
while  [ "$COUNTER" -le 20 ];
do
	echo "$COUNTER"
	case "$COUNTER" in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	COUNTER=$((COUNTER+1))
done
