#!/usr/bin/env bash
# bash scrip that gives info about school file
file="school"
if [ -e $file ]
then
echo "$file file exists"

if [ -s $file ]
then
	echo "$file file is not empty"
else
	echo "$file file is empty"
fi

if [ -f $file ]
then
	echo "$file file is empty"
fi
else
	echo "$file file dose not exist"
fi
