#!/usr/bin/env bash
# bash scrip that gives info about school file
if [ -e school ]
then
echo "school file  exists"
if [ -s school ]
then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f school ]
then "school is a regular file"
fi
else
echo "school file dose not exist"
fi

